apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployments
  labels:
    name: postgres-voting-dp
spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
       containers:
        - name: postres
          image: postgres:9.4
          ports:
           - containerPort: 5432

  selector:
    matchLabels:
      name: postgres-pod
       app: demo-voting-app
  replicas: 3


